[
  {
    "p_id": 5,
    "p_date": "2022-09-14T19:41:22.000Z",
    "p_title": "My First ads",
    "p_brand": "Sanaulla",
    "p_describe": "Hello",
    "p_img1": "image 1",
    "p_img2": "image 2",
    "p_img3": "image ",
    "p_img4": "image 4",
    "p_img5": "image 25",
    "p_price": 500,
    "p_location": "solapur",
    "p_mcat": 1,
    "p_scat": 2,
    "p_uid": "111",
  },
  {
    p_id: 6,
    p_date: "2022-09-14T19:41:26.000Z",
    p_title: "My First ads",
    p_brand: "Sanaulla",
    p_describe: "Hello",
    p_img1: "image 1",
    p_img2: "image 2",
    p_img3: "image ",
    p_img4: "image 4",
    p_img5: "image 25",
    p_price: 500,
    p_location: "solapur",
    p_mcat: 1,
    p_scat: 2,
    p_uid: "111",
  },
  {
    p_id: 7,
    p_date: "2022-09-14T19:41:29.000Z",
    p_title: "My First ads",
    p_brand: "Sanaulla",
    p_describe: "Hello",
    p_img1: "image 1",
    p_img2: "image 2",
    p_img3: "image ",
    p_img4: "image 4",
    p_img5: "image 25",
    p_price: 500,
    p_location: "solapur",
    p_mcat: 1,
    p_scat: 2,
    p_uid: "111",
  },
];
